### ISSUE TITLE
Create 18F blog art guidance

### ISSUE THREAD

**Issue by cmajel** [18F/TLC-crew#120]
### A description of the work
[18F blog posts](https://18f.gsa.gov/blog/) have an option for banner art, but often these banners reuse images designed for inline content. This results in banners that can be cut off and obscured, and also varying preview sizes in the blog feed.

This art can be abstract and conceptual, but it should not appear broken or unidentifiable.

This work would include:
* Creating templates and/or guidance for creating blog illustrations in the future
* Deciding where authors should encounter this guidance ([blog drafts repo](https://github.com/18F/blog-drafts)? [draft blog issue template](https://github.com/18F/blog-drafts/issues/new?assignees=&labels=blog&template=blog-post-idea.md)? elsewhere?)
* Evaluating if there are changes we can make to the existing banner display that would work better for existing blog art

Related items that could be extensions of this work in future tickets:
* Review the most viewed blog posts and adjust banner art if needed
* Explore guidance for social media assets
* Develop a style or illustration guide for blog art to reinforce a cohesive 18F style (what do we say no to? how do we encourage cohesion with the resources we have?)
* Evaluate if the blog previews on the[blog feed](https://18f.gsa.gov/blog/) should be redesigned based on banner art decisions

### Point of contact on this issue
You can reach out to me, @cmajel. I can assist in connecting with website contacts as needed.

### Reproduction steps (if necessary)
Examples of blog art sizing:
Cut off: 
* [Introducing the U.S. Web Design Standards](https://18f.gsa.gov/2015/09/28/web-design-standards/)
* [Buying Christmas tree permits online with Open Forest](https://18f.gsa.gov/2019/02/12/open-forest-launch-post/)

Cut off, but still conceptual:
* [The 18F engineering sandwich for cloud based web apps](https://18f.gsa.gov/2022/09/06/18f-tech-sandwich/)
* [Creating a culture of innovation at your agency](https://18f.gsa.gov/2022/09/12/creating-a-culture-of-innovation/), 

Designed for current container: 
* [A federal guide to de-risk government technology projects](https://18f.gsa.gov/2020/09/09/a-federal-guide-to-de-risk-government-technology-projects/)
* [Six years improving the experience of government](https://18f.gsa.gov/2020/03/19/sixth-anniversary/)
* [READMEs for you and me](https://18f.gsa.gov/2020/03/05/readmes-for-you-and-me/)
* [Transforming how DOJ's Civil Rights Division engages with the public](https://18f.gsa.gov/2020/07/07/transforming-how-dojs-civil-rights-division-engages-with-the-public/)

Here's the [blog feed](https://18f.gsa.gov/blog/) and a sample preview:
<img width="716" alt="Screen Shot 2023-04-06 at 3 41 54 PM" src="https://user-images.githubusercontent.com/2374206/230480592-49c2e3f9-3d8c-41fd-9686-8549a6655be9.png">

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [x] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
Around 2 weeks

### Acceptance Criteria

- [ ] As an 18F blog author, I want to easily learn what size and design requirements I need to consider so that I can create a blog banner image (or decide to skip it).

- [ ] As an 18F blog reader, I want to art on a post to reinforce the content of the blog and be identifiable so that I don't feel I'm lost or the site is broken. 

### Tasks
- [x] Draft blog art guidance in a Google doc
- [x] Share with @cmajel for review
- [x] Refine draft based on feedback
- [x] Create a pull request to publich the blog art guidance to the blog repo's README https://github.com/18F/blog-drafts
- [x] Tag @MelissaBraxton, @cmajel, and @LizCamerlin as reviewers

**Comment by MelissaBraxton** [comment]
@HannaSChang  - I added a task list to make it clear how to get this to done.

**Comment by HannaSChang** [comment]
@cmajel The [18F Blog Art Guidance draft](https://docs.google.com/document/d/1I9bmN_Pd5kXPQEoE4NMZdQy1CpZ6AtNzsyQGYJE9pQo/edit?usp=sharing) is ready for your review! I included some notes/comments/questions in some sections. Feel free to reach out to me with any feedback or questions.

@MelissaBraxton will be creating separate issues for the related tasks in this ticket:

- Evaluating if there are changes we can make to the existing banner display that would work better for existing blog art

- Review the most viewed blog posts and adjust banner art if needed

- Explore guidance for social media assets

- Develop a style or illustration guide for blog art to reinforce a cohesive 18F style (what do we say no to? how do we encourage cohesion with the resources we have?)

- Evaluate if the blog previews on the [blog feed](https://18f.gsa.gov/blog/) should be redesigned based on banner art decisions

**Comment by cmajel** [comment]
I added a few comments and suggestions for clarity.

**Comment by HannaSChang** [comment]
Thank you, I see them! Will take a look and update the guidance.

**Comment by HannaSChang** [comment]
@cmajel The blog art guidance has been updated based on my conversations/feedback with Melissa, Liz, and Aviva. When you have a moment, would you be able to take one more look and let me know if this looks good or needs anymore clarification? Thank you!

**Comment by cmajel** [comment]
🎉 🚀 Looks good to me!

**Comment by HannaSChang** [comment]
PR has been created for blog issues template - [862](https://github.com/18F/blog-drafts/pull/862)
And also for the blog-drafts README - [863](https://github.com/18F/blog-drafts/pull/863)

I wasn't sure how to combine these into one PR so I created two. I also tagged @cmajel, @LizCamerlin, and @MelissaBraxton as the reviewers. Let me know if you have any questions!
