### ISSUE TITLE
Change the name of this group from DA-team to 18F-TLC crew

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#142]
### A description of the work
This issue covers announcing the group's name change in all the appropriate challenge and updating documentation and artifacts to reflect this change.

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [ ] No

How much time do you anticipate this work taking?
3 days

### Acceptance Criteria

- [x] We've replaced mentions of the DA-team w/ 18F TLC crew in our documentation and artifacts 
- [ ] We've announced this change to relevant groups and in all relevant channels

### Tasks
 - [x] Determine where and how to announce the name change
 - [x] Update Slack channel name
 - [x] Review repo and replace DA-Team references with TLC-team
 - [x] Review documentation in reusable Docs, sheets, and slides and replace DA-Team references with TLC-team

**Comment by MelissaBraxton** [comment]
@alexbielen  - This is something that really anyone on the team can do if it turns out folks have extra bandwidth next increment.

**Comment by annepetersen** [comment]
I just added #184 which is certainly related: if it's repetitive, feel free to delete it

**Comment by MelissaBraxton** [comment]
@alexbielen  - Do you think we need to announce the name change beyond the announcements that have already been made? I feel like with various Slack notes from Kelsey and Alan and with our TC preso last week, the cats already out of the bag. If you agree, then I think we can call this done after you spot check to make sure I haven't missed anything.

**Comment by alexbielen** [comment]
@MelissaBraxton I think that the presentation from the last TC covers it, yup!
