### ISSUE TITLE
Update wiki to reflect changes w/ introduction of team leads

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#143]
### A description of the work
This issue covers reviewing the Github README and wiki and ensuring that they accurately describe this group's practices.  A lot of little things have changed in the past few weeks. 

### Point of contact on this issue
@MelissaBraxton and/or @alexbielen 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [] No

How much time do you anticipate this work taking?
2 days

### Acceptance Criteria
- [x] The wiki matches the team's current practices

### Tasks
- [x] Create a doc to suggest edits to current wiki and README content
- [x] Peer reviews
- [x] refine based on feedback
- [x] Make changes in Github

ex: As an 18F staff member who is going on parental leave, I can navigate to my
latest Tock reporting period and choose billing line #1810 by filtering by
number or "extended OOO"
