### ISSUE TITLE
Draft near and mid-term roadmap

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#152]
### Point of contact on this issue
Who can we follow-up with if we have questions?

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [ ] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [ ] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [x] The DA team leads and LT representative have a roadmap that will assist them in prioritizing work and set goals for each increment over the next 3-6 months
- [ ] The roadmap is documented in a place that is easy to access
- [x] We've documented our practice of revisiting the roadmap at regular intervals

### Tasks
- [x] Plan and facilitate roadmapping discussion with @kfoley-18F, @alexbielen, and @MelissaBraxton 
- [x] Document outputs  
- [x] Review with Chief of Delivery
- [x] Document follow on work as new issues

**Comment by MelissaBraxton** [comment]
@donnykwan  - Let me know if scheduling is a challenge, and we can see about shuffling events around to find a time that works!

**Comment by donnykwan** [comment]
Let's  keep the scheduled meeting this Friday, I will take another day as AWS.

**Comment by alexbielen** [comment]
@MelissaBraxton and I discussed this. 

As a part of #152 we are trying out a new way of discussing larger initiatives. We are going to wait until we've done a few of these before we abstract it into a template that is useful for this group.

**Comment by alexbielen** [comment]
Moving to ICEBOX for now.

**Comment by alexbielen** [comment]
Disregard the previous two comments! Meant for a different ticket.
