### ISSUE TITLE
Create a google form for onboarding folks

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#159]
### A description of the work
For folks onboarding, we want to learn about their skills, capacity, and work preferences prior to having our initial onboarding meeting so we can focus on meeting new members of the TLC Crew where they are at. We also want to give folks onboarding time to reflect on these things and answer in writing, rather than possibly feeling put on the spot in a group mtg. 

We recently auditioned this as a video call with new TLC Crew members. The questions that we asked were:

- Tell us about your capacity and energy level?
- What types/shapes of work are you needing right now?
- What are your comfy core skills? 
- Any skills you are interested in growing?

### Point of contact on this issue
@alexbielen or @MelissaBraxton 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [ ] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [ ] We have a Google form that asks all the Qs team leads need to consider how to best match incoming folks to the work on deck
- [ ] Form responses are private to respondents and team leads

### Tasks
 - [x] Get list of possible Qs to ask from team leads
 - [x] Create Google Form in TLC Crew Team Folder
 - [x] Ping @alexbielen and @MelissaBraxton to review
 - [ ] Refine form based on feedback

**Comment by egamble23** [comment]
Hi @alexbielen and @MelissaBraxton , here's a draft of the text for onboarding folks. I have it in Google Docs right now since it may be easier to do edits/comments in that. 

https://docs.google.com/document/d/1RZ5DdxUioS9u7_iJhR0ifDr1cKRb_kAkGTc8dL7lLxQ/edit?usp=sharing

Please have a look and warmly welcome edits/refinements/changes! 

For tone, I wrote it as friendly/upbeat, but I can go for another angle if that fits better (warm/formal/etc.). All good, just let me know what may work!

I'll work on moving the draft into a Google Form later today after some meetings. Thanks!

**Comment by MelissaBraxton** [comment]
Hey there, Erin! I reviewed the doc, and it's looking good to me. I'd say go forth and make a draft Google form, and we can put on any finishing touches from there!

**Comment by egamble23** [comment]
Thanks so much, @MelissaBraxton  and @alexbielen, for your edits in the Google doc!

I've created a draft Google Form in this folder: https://drive.google.com/drive/folders/1oV-qZFigc0mliSHOQhuBwozPqNmK9JVB?usp=sharing

I put it in the Team Leads folder since the answers are for you both. However, I'm not sure if there is a way to limit access to that subfolder. It may be the folder may need to be located somewhere else or the form to be copied by one of you with limiting access to it.

Anyway, please have a look! All good to further refine as needed. It may be nice to also run it by a few new TLC team members for their reactions/suggestions.

**Comment by MelissaBraxton** [comment]
This looks good to me!

I've adjusted the permissions on the response folder

I think we can move this to done for now.

**Comment by egamble23** [comment]
Okay, great! Thanks so much.
