### ISSUE TITLE
Update 18F Federalist Page

### ISSUE THREAD

**Issue by cmajel** [18F/TLC-crew#160]
### A description of the work
We have this case study about Federalist on the 18F website. But, there are few fixes to improve the accuracy and experience of this page:

Example of alignment issue: 
<img width="1160" alt="Screen Shot 2023-04-17 at 5 05 20 PM" src="https://user-images.githubusercontent.com/2374206/232610937-5be3981f-931b-42e3-8f81-37a6fe650c4b.png">

### Point of contact on this issue
Who can we follow-up with if we have questions?

You can contact me, @cmajel. I can help connect with website contacts as needed.

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

A designer with front-end experience could contribute here too. 

- [ ] Any human
- [x] Design
- [x] Content
- [x] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [x] Visitors to the 18F Federalist page know that 18F Federalist is now cloud.gov pages and is not maintained by 18F. 

### Tasks

- [x] Update content to note that Federalist is now [Cloud.gov](http://cloud.gov/) pages, and not maintained by 18F
- [x] Update sidebar labels appropriately. 

_- Fix section and aside alignment to match other page elements (this is an issue across [case study content](https://18f.gsa.gov/what-we-deliver/forest-service/)). This appears to affect mostly screens wider than 1030px. --> Note, this has been moved to a [separate issue](https://github.com/18F/TLC-crew/issues/183)._

**Comment by alexbielen** [comment]
Increment planning risks, concerns, changes: 

- Who is the owner for this page?
- Confusion about this ticket: is this bigger than just updating the content? This is on the 18F website but we do not actively operate Cloud.gov pages. Is there a more appropriate way or place to talk about this?
- Understanding the justification for priority on this one might be helpful
- If we keep maintaining this we accrue a maintenance cost. Is there a different approach here? Could we redirect to current Cloud.gov Pages documentation. 
- Is this a stub page that is like "18F built this but we don't own it -- check it out over at its new home".
- Check in with ticket owner @cmajel about this one. 

- Should this task "Fix section and aside alignment to match other page elements (this is an issue across [case study content](https://18f.gsa.gov/what-we-deliver/forest-service/)). This appears to affect mostly screens wider than 1030px " be a separate ticket?

**Comment by cmajel** [comment]
@alexbielen saw this note and I'm happy to clarify what I can. Here's some context on why I submitted this ticket: 

* I came across this page when trying to explain Federalist to a new 18Fer. It was my top google result when I searched "GSA Federalist". 
* I then cross checked [the top pages for the 18F website in the last year](https://docs.google.com/spreadsheets/d/1Q9p72xbEQDyVQVpKh5qmHD5nbS9sZJ73zF6g3v-q0nc/edit#gid=567805071). It was the 50th page for pageviews, which, feels like something so I created this ticket (but also top 100 is just a line I drew)
* Looking at this again, there is a similar [USWDS page](https://18f.gsa.gov/what-we-deliver/us-web-design-system/) that has a similar ranking. Though, this page feels less inaccurate. But it still falls into your questions of "should this exist"

My goal here was to flag a content inaccuracy, though I agree that there are bigger questions about maintenance and how to represent past projects on the site. I can give my opinions, but I don't see myself as owning that decision. (Something for LT or future site PO?)

**Comment by MelissaBraxton** [comment]
Tagging in @amandacostello and @durland18F since it aligns with your efforts to make the content on the site more current. 

@egamble23  - To your Q re: who can make content changes, since it's 18F's website, once you have drafted potential content changes, you can submit a pull request to the 18F site repo. If you run into blockers re: getting content changes reviewed, feel free to tag in @kfoley-18F.

**Comment by egamble23** [comment]
Many thanks, @MelissaBraxton , for your comment and clarifications! 

I'm coordinating with @amandacostello and @durland18F  for next steps on this 18F Federalist page's treatment.

As part of that, it makes sense to us to separate this technical issue from the original ticket ("Fix section and aside alignment to match other page elements (this is an issue across [case study content](https://18f.gsa.gov/what-we-deliver/forest-service/)). This appears to affect mostly screens wider than 1030px"). 

To meet that request need, I'll submit a new ticket for this technical issue and reference this ticket for context.

**Comment by egamble23** [comment]
Hi @kfoley-18F ! After discussing with @amandacostello and @durland18F, we'd like to propose making this 18F Federalist Page a stub page that redirects to Cloud.gov. 

It's a little unclear about who would "own" this decision about a stub page approach (vs. another approach). Would you be able to advise on how that decision could be made and who I can check with for the go-ahead? Would that be something you or LT could approve? Or would I need to contact Cloud.gov folks?

I can run by the draft stub page content by folks, just wish to check in on the stub page approach before getting too far in one direction. :) Thanks!

**Comment by kfoley-18F** [comment]
@egamble23 - sounds good. This is an 18F site in an 18F repo, so we can just change it. Make the change in a Github branch, and have it reviewed by @amandacostello and @durland18F and ship it!

If you're worried about having Cloud Pages folks involved, you can ping @drewbo to take a look when you have made the change.

**Comment by drewbo** [comment]
@egamble23 hi! happy to review from a cloud.gov Pages perspective, feel free to tag me on the PR

**Comment by egamble23** [comment]
Here is the stub page approach that @durland18F and I worked on yesterday: https://docs.google.com/document/d/1MXJCS3u_yCwpGHom6wpaP53_4U94IRGb9aD5xG75I5E/edit?usp=sharing. 

Will be putting the changes into GitHub during co-working today for reviews and making it live.

**Comment by egamble23** [comment]
Hi @drewbo! 
Before submitting the PR for review for you, could you weigh in on for the stub page's copy reading "cloud.gov" or "cloud.gov Pages"?

_Draft text:_

Federalist is now cloud.gov Pages

The platform formerly known as Federalist is now [cloud.gov Pages](https://cloud.gov/) — a fast, secure, and compliant Platform as a Service (PaaS) for federal agencies. It is no longer maintained by 18F.

Visit [cloud.gov](https://cloud.gov/) to learn more.

**Comment by egamble23** [comment]
Thanks @drewbo ! I've woven in your feedback from the Google doc into the pull request. I'll tag for your review along with @amandacostello , @durland18F , and @cmajel .

Many thanks to all for your help and patience! This is my first pull request in GitHub. Please reach out if there are any questions or if I need to do another step.
