### ISSUE TITLE
Review, refine, and reorganize an inventory of links to existing content and resources by documented project phases

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#175]
### A description of the work
We hypothesize that organizing our resources, methods, and guides around our 18F project phases will help us achieve our strategic bets ([LT update deck for reference](https://docs.google.com/presentation/d/1blkbjomC4v_lx4jjgVT08Qgi4oetMvNzwMpKSgZhisA/edit#slide=id.g1bfeff297f0_0_231)) and will better meet the needs of new 18F staff (rather than external audiences)
This issue is a first step towards testing that hypothesis.

The scope of this issue is reorganizing and possibly expanding on an existing index/inventory of our resources, guides, and methods organized by project phase. This work is an expansion of the  [Draft delivery school outline](https://docs.google.com/document/d/1-yPhvggQLzeGJBmbLRa5MHoXtSCmJTw68Es7ZcIUayI/edit#heading=h.21rnprk0d00) and may inform refinements to the proposed information architecture that was drafted by the former Guides and Methods team.

### Point of contact on this issue
@kfoley-18F, @alexbielen, and @MelissaBraxton  

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [X] Design
- [X] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [ ] No

**How much time do you anticipate this work taking?**
2 days

### Acceptance Criteria
- [ ] We have a refined information architecture that maps to project phases 

### Tasks
- [x] Review background material 
    - [x]  proposed information architecture from Methods and guides work: [sheet](https://docs.google.com/spreadsheets/d/1p-qz4tctoRItMkrINCwo5A5cE4d_98ofkLO2qcO96mY/edit#gid=0), and [Mural](https://app.mural.co/t/gsa6/m/gsa6/1668097098114/878e1c014d808b0a1fd2e158c06249a1d9f2ecf7?invited=true&sender=melissabraxton2796)
    - [x]  [Draft delivery school outline](https://docs.google.com/document/d/1-yPhvggQLzeGJBmbLRa5MHoXtSCmJTw68Es7ZcIUayI/edit#heading=h.21rnprk0d00)
    - [x] [18F standard project phases/outcomes](https://docs.google.com/document/d/1GTyor4wV87QXLIutMh__pg0FZTG--NY9XCfvdlFw6fQ/edit)
- [x]  Refine and expand the delivery school outline so that it is: (1) organized around 18F project phases (2) highlights any places where we have few or no resources to map to a particular phase or activity, and (3) embodies testable hypotheses about how it's optimized for the needs of 18F staff (rather than external users)
- [x] Share with @kfoley-18F, @MelissaBraxton and @alexbielen for review and for help convening additional stakeholders to review as needed.  
- [x] Write down findings/challenges with this
- [x] Create a new issue to test hypotheses

**Comment by alexbielen** [comment]
Risks and suggested changes from Sprint Planning:

- Spell out or break out "identify knowledge gaps". It is currently somewhat unclear what this means and what success looks like. 
- AC is referencing the Delivery School Draft outline and it may not be clear how that relates to everything in here. 
- Pointing out a risk: not an 100% consistent shape with what projects might look like. Are there ways to generalize this?
- The 18F standard project phases and outcomes document is not widely accessible
- Risk that we need some additional feedback from the content guild that we could get. 
- Could this be accomplished by someone who has lots of experience with 18F project phases with someone that has "content organization"skillset? 


An FYI from Donny:
- De-risking guide is the so-called "starting point" for the new guides work.

**Comment by MelissaBraxton** [comment]
Note that parts of the IA proposed by the guides and methods team is dependent on the SSG we chose having the ability to have sidebar content or blocked content - if this is not possible technically feasible than this will mean more work!

**Comment by MelissaBraxton** [comment]
I updated this to make it clear that the MVP here is a reorganization and possibly expansion of the existing inventory in the delivery school outline. (rather than starting from scratch)

I also realized that the timing/effort estimate had not been updated since this was scoped much more broadly a few weeks back, so I updated that to reflect the narrowed scope.

**Comment by MelissaBraxton** [comment]
Hey there, @janelx and @austinhernandez  - I wanted to add the link to the [team toolkits 1 pager](https://docs.google.com/document/d/1r93cXSUdORAWCQR1dLtVMl3fD3LYd-E-eyxT_HKWuIA/edit#) we looked at during increment planning so that y'all can keep this context in mind in case it's helpful!

**Comment by alexbielen** [comment]
FWIW, I think it's normal that many of them will fit into multiple phases. No need to put them into just one phase. Would love to see what overlaps as well!

**Comment by austinhernandez** [comment]
Here is the rough  [18F resources by project phase document](https://docs.google.com/document/d/1j2v99Ff-WdeU9h5-n2GfNmwuf3oJMtHnaPi3CPecarA/edit#heading=h.p505k5gqu7fq). Again, stressing _**ROUGH**_ because follow on work is in #224. Janel and I  combined resources and put them in the phases we thought they should go using an educated guess. Additional work will need to be done to find a proper home for a final version

**Comment by MelissaBraxton** [comment]
@austinhernandez , @janelx Requested access

**Comment by MelissaBraxton** [comment]
I left some comments in the doc and found time for us to meet tomorrow to talk through remaining steps.

**Comment by MelissaBraxton** [comment]
Thanks @janelx  - This meets the acceptance criteria for this issue. I created #236 to cover making the additional improvement we talked about when we last met to show which resources map to the common activities, but that's technically outside the scope of this issue, so we can call this done for now.
