### ISSUE TITLE
Rolling out Google-based accessible deliverables checklist

### ISSUE THREAD

**Issue by egamble23** [18F/TLC-crew#180]
Related to [issue #87](https://github.com/18F/delivery-assurance/issues/87) on Google-based accessible deliverables guidelines. (This issue replaces the earlier 858 blog post ticket with clarified ticket guidance and scope based on updated information.) 

A description of the work
Rolling out new accessibility [checklist](https://docs.google.com/document/d/1aQfHNGAwwOaBGllGeZ9_xA5aeYd3Ak6TQL4-M8B5SVg/edit) for Google-based deliverables

Audience
- colleagues new to 18F
- 18F colleagues who create deliverables in Google tools for partners and need them to be accessible

Point of contact on this issue
@egamble23, @lauranash18f, @AnnabelLombard, @awichman   

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [X] Design
- [X] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?
- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
Under 2 weeks

Acceptance Criteria
 - [x] Have implemented socializing the Google tools accessibility checklist for new 18F colleagues in the handbook and other onboarding spaces, as appropriate

### Tasks
- [x] Coordinate with Accessibility Leads for their guidance about placing the link or content of the Google tools accessibility checklist as part of the handbook's accessibility [page](https://handbook.tts.gsa.gov/getting-started/classes/accessibility/)
- [x] Implement placing link or content into the handbook, as appropriate
- [x] Coordinate with Jason Nakai, Mike Matis, and Gerardo Cruz-Ortiz regarding the new checklist as a possible additional resource for their accessibility trainings for new colleagues
