### ISSUE TITLE
Updating Accessibility Guild Leads' names in handbook

### ISSUE THREAD

**Issue by egamble23** [18F/TLC-crew#181]
A description of the work
Update Accessibility Guild Leads' names in TTS handbook: https://handbook.tts.gsa.gov/getting-started/classes/accessibility/

Point of contact on this issue
Accessibility Guild Leads Mike Matis and Jason Nakai 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [X] Design
- [X] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?
- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
1-3 day

Acceptance Criteria
 - [ ] Have updated the names on the page https://handbook.tts.gsa.gov/getting-started/classes/accessibility/

### Tasks
- [ ] Coordinate with the new Accessibility Guild Leads Mike Matis and Jason Nakai on their preference on updating the page
- [ ] Updating the page

**Comment by michelle-rago** [comment]
Guild leads need to be updated on https://handbook.tts.gsa.gov/training-and-development/working-groups-and-guilds-101/#guilds-in-tts-2.
