### ISSUE TITLE
Update project health form

### ISSUE THREAD

**Issue by janelx** [18F/TLC-crew#187]
### A description of the work
Project Health has been done differently by different 18F teams, and this means that the data collected isn't consistent or useful for the intended outcomes. LT members and AMs have tried to rework PH, but this hasn't landed.
We need a single way to collect Project Health information on a consistent reporting cadence across 18F teams (the start of "the 18F Way") so that all the stakeholders for PH information find it valuable and so that we have one process to iterate on instead of reinventing wheels.
We also need a plan to communicate and roll this out as change management across 18F.

### Point of contact on this issue
@SelenaJV will be Manager and Approver (in MOCHA framework)
@Erica-Perkins should be Consulted

### Reproduction steps (if necessary)
DA Team couldn't figure out how to do PH among the myriad ways already present in 18F. 
LT already struggles to understand and make good use of PH reported data. 
This process isn't working for anybody. 
We need to fix it. 

**Billable?**
- [ ] Yes
- [X] No

**Skills needed**

- [X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [X] Other: Account Management

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
Likely a full 2 weeks. 

### Tasks
- [x]  Learn more about project leadership presentation (Colin Murphy)
- [x]  Learn more about project phases (Laura Gerhardt)
- [x]  Update Project Health Form- based on feedback ([currently working on/ a work in progress])
- [x]  Update Project Health Readme / combine w/form
- [ ]  Document different ways to facilitate answer project health
- [ ]  Update airtable views/create a dashboard - consult w/Kelsey (SME)
- [ ]  Review form: Share and gather feedback from Selena, Erica P., & account managers
- [ ]  Document new issue(s) to cover next steps

### Acceptance Criteria
 We have a first draft of a revised project health form and README that has been shared with stakeholders for feedback
 We've documented facilitation guidance for the new form

**Docs**
[Project health discovery and planning notes](https://docs.google.com/document/d/1hZAmc3sEBsgwErqq37qyvmLvcrPA25SDnQ-e430FNSo/edit#heading=h.tn2eb9uomeec) - Outlines background, goals and values of project health (in progress). 
[Project Health form - Working draft](https://docs.google.com/document/d/1FxJFvS4O36awr0j90DabBvohDJjWkgincxFF_1EykZM/edit)

**Comment by janelx** [comment]
Update: Form has been created and updated based on initial feedback. Optional: For MVP we can remove the link to the incomplete document of ways to facilitate and add it back once it's completed.
 
@MelissaBraxton since this ticket isn't completely checked off and the sprint is coming to close, would you like me to create new tickets or keep the current one open. If we create new tickets I think it'd make sense to split the work as such:
**Ticket 1**
Create airtable project health form and dashboard (consult w/Kelsey)
Gather feedback from stakeholders: Selena, Erica, Andrew and AMs - maybe additional supes?
Test with a few project teams
Share with 18F (may be it's own ticket - depending on timing)

**Ticket 2**
Discover and document different ways to facilitate completing project health form as a team

**Comment by MelissaBraxton** [comment]
Thanks @janelx! Let's make 2 new tickets, and I'm on board the way you've broken them out.

**Comment by janelx** [comment]
I've created the tickets. @SelenaJV here are the new tickets for Project Health updates. Please feel free to edit them or let me know if you'd like anything udpated.
[Create Project Health form in airtable, gather feedback and update#226](https://github.com/18F/TLC-crew/issues/226)
[Project Health: Discover and document different ways to facilitate#227](https://github.com/18F/TLC-crew/issues/227)

**Comment by MelissaBraxton** [comment]
@janelx  - I believe this is done now then? Once we update the task list / remove tasks that are now part of new issues?

**Comment by janelx** [comment]
Sounds good. I just wanted to make sure @SelenaJV is tagged in case she would like to review and easily find how next steps are being organized into those two tickets.
