### ISSUE TITLE
Document processes for communicating back to issue authors

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#195]
### A description of the work
This work covers documenting and communicating a process for reviewing incoming and existing issues submitted by folks outisde the team and communicating back to issue authors what they can expect. This likely includes how we'll determine a rough timeframe in which we might be able to do the work, how we'll inform issue authors, and a process for removing submitted issues that we won't be able to take on in an acceptable timeframe.  

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [ ] No

How much time do you anticipate this work taking?
4 hours

### Acceptance Criteria

- [ ] We've documented a process in the wiki
- [ ] We've communicated this process to relevant stakeholders

### Tasks
- [x] Draft process documentation
- [x] Share for feedback from a few issue authors who will likely be users of the process (AMs, product owners, etc.)
- [x] Refine based on feedback
- [ ] Document process in wiki
- [ ] Share as part of team coffee preso on 5/19

**Comment by alexbielen** [comment]
@MelissaBraxton I'm feeling good about the "Draft process documentation" step but let's review in our sync tomorrow so that we can start sharing this out.

**Comment by alexbielen** [comment]
[Link to the draft](https://docs.google.com/document/d/1vfwMQ7N2erovpgZ7ypGtApSYsCBzqjELU_MmbRDI13c/edit#). 

We shared with @rrefoy @juliaklindpaintner @beechnut for feedback from issue authors.

**Comment by MelissaBraxton** [comment]
@alexbielen  - We've addressed feedback from 2 of the 3 folks, and I've put the refined content in the draft wiki update doc. Given that we're not on the agenda for this week's team coffee after all, how do we want to get this to done? Can we change the tasks to announce it via Slack instead? Is #18f the right channel?

**Comment by alexbielen** [comment]
I like the idea of the `#18f` channel!
