### ISSUE TITLE
Document 18F doctrine on preparing products to launch: safely putting an already-compliant product into use.

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#197]
### Problem statement
Government teams broadly do not have guidance on how to safely launch new software. Partner agencies are often unaware of the value of beta tests, incremental trials, and rehearsing operations. 18F teams have recognized this need, but may not know what existing resources they can draw upon. 18F does not have best practice guidance for teams to consider.

### A description of the work
Long-term vision: Any government software team can find 18F resources that provide accessible, actionable best practices to reduce the risk of unsuccessful product launches.

#### Roadmap (draft):
*Now*
- [x] Document the existing resources used by product teams preparing for launch
- [ ] Add document to #project-resources
- [ ] Internal announcement so people know they can look for it
- [x] Document next steps a new issue - #218

### Point of contact on this issue
 - @cjhskippy (proposing work)
 - TBD (owner of guides + methods)

### Reproduction steps (if necessary)
N/A

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [x] Content
- [x] Engineering (maybe?)
- [ ] Acquisition
- [x] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [ ] 18F staff can find existing resources on preparing products to launch added from the project resources folder
- [ ] All tasks under **"now"** are completed

**Comment by MelissaBraxton** [comment]
This looks great, @cjhskippy! I'd consider what you have under "now" the scope for this increment. I made a few tweaks and added a task to document next steps as a new issues. I'd imagine that the next issue will look a lot like what you have under "next," but that it might change based on what you learn by doing what listed under now. How does that sound?

**Comment by cjhskippy** [comment]
I'm all for starting small and adjusting once we know more. In this case, I think the effort for the "now" section is maybe 1-2 days of working time, spread out over a few more days pending any review on internal comms.  I already have a head start on the resource list after making the inquiry in the #18f channel.

**Comment by julialeague** [comment]
One thing I'm aware of that exists on this subject is this section in the TTS handbook: https://handbook.tts.gsa.gov/#launching-software

**Comment by cjhskippy** [comment]
@julialeague Thank you for mentioning it! I'd taken a look earlier, and while most of that content is pre-launch (implementing compliance controls + navigating ATO), this section has some excellent material that I had overlooked: https://handbook.tts.gsa.gov/launching-software/infrastructure/#good-production-practices

**Comment by cjhskippy** [comment]
Existing resources that I was able to compile are now in the [18F Resources by Project Phases](https://docs.google.com/document/d/1j2v99Ff-WdeU9h5-n2GfNmwuf3oJMtHnaPi3CPecarA/edit#) document.

Next steps:

- Edits need review
- Newly-added resources are NOT yet in the Project Resources airtable - likely should be included there too
- Once finalized, we should publicize existence
- Updated issue #218 w/ recommended next task: a gap analysis to identify activities in launch preparation that do not have existing resources or how-to guidance
