### ISSUE TITLE
Improper heading order for headings of the lists of links on 18F home page

### ISSUE THREAD

**Issue by jasnakai** [18F/TLC-crew#199]
# ISSUE: Improper heading order for headings of the lists of links on 18F home page  
Related to: #121 
## Brief description
The headings for the list of links at the bottom of the page (see Image 1) are currently `<h4>`s which would make them children of the previous `<h3>` (Am I doing it right? A check up for agile teams) which they aren't. They should be `<h2>`s as they are not children of the previous `<h2>` (Recent blog posts) either.  

Image 1. 
![Image](https://user-images.githubusercontent.com/106776019/236731924-b5ae92fc-0906-41a9-af0c-47d3db8907fe.png)

## Standards
* [1.3.1 Info and Relationships (WCAG2.0 A)](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#content-structure-separation-programmatic)

## Steps to Reproduce
Check the source code for the 18F home page. Review the heading structure.
Or use a heading/outline checker such as this heading outliner bookmarklet (https://hinderlingvolkart.github.io/h123/)

### Expected
Headings and content follow a proper structure.

### Actual
Heading and list of links are coded as children of the previous `<h3>` (Am I doing it right? A check up for agile teams) which they aren't.

***
## Acceptance criteria
- [x] Update the headings for the list of links to a proper heading level (ie. `<h2>`).

## Tasks
- [x] Create a pull request with issue remediated
- [x] Tag @alexbielen as a reviewer

**Comment by jasnakai** [comment]
Closing this since it is Done.
