### ISSUE TITLE
18F website tab order is broken at the footer

### ISSUE THREAD

**Issue by jasnakai** [18F/TLC-crew#200]
# ISSUE: 18F website tab order is broken at the footer  
Related to: #121 
## Brief description
The tab order is broken near the footer area of the [18F website](https://18f.gsa.gov/) due to the footer reordering itself. The reordering is being caused by the CSS order rule.

## Standards
* [2.4.3 Focus Order (WCAG2.0 A)](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#navigation-mechanisms-focus-order)

## Steps to Reproduce
Use the keyboard to navigate through the focusable elements on the 18F home page. Notice that when you reach the footer area, the logical order is broken.

### Expected
Users can navigate through the focusable elements on the page in a logical visual order (right to left, top to bottom).

### Actual
The focus order is disrupted near the footer area.

***
## Acceptance criteria
- [x] Focus order follows the logical visual order of right to left, top to bottom.

## Tasks
- [x] Create a pull request with issue remediated
- [x] Tag @alexbielen as a reviewer

**Comment by jskinne3** [comment]
Fixed via this PR, now merged: https://github.com/18F/18f.gsa.gov/pull/3695

**Comment by jasnakai** [comment]
Closing this since it is done.
