### ISSUE TITLE
Remediate 18F website global accessibility bugs

### ISSUE THREAD

**Issue by jasnakai** [18F/TLC-crew#212]
### A description of the work
This work is based off of findings from an accessibility audit performed for ticket [#121](https://github.com/orgs/18F/projects/41/views/1?pane=issue&itemId=25040967). 
Documentation of accessibility bugs can be reviewed and [found here](https://docs.google.com/document/d/1LdVHKATsF6I3Ylc4MO9c7wDHHFgTwZ1yYWfUvLUDThU/view).

List of bugs:
- 18F website tab order is broken at the footer
  - Ticket already created: #200 )
- Improper heading order for headings of the list of links at the bottom of page
  - Ticket already created: #199 )
- Ill formatted `<main>` element 
- Remove unneeded ARIA `role` attributes

### Point of contact on this issue
- @jasnakai

### Billable?
- [ ] Yes
- [x] No
If yes, tock code:

### Skills needed
- Frontend Dev

### Acceptance Criteria
- [x] Remediate the documented accessibility issues 

### Tasks
- [x] Create a pull request with issue(s) remediated
- [x] Tag @jasnakai and @alexbielen as reviewers

**Comment by jasnakai** [comment]
Update: The first two issues have already been completed on separate tickets. The `<main>`  tag is an part of the USWDS and will be addressed there. 
Creating a PR for the `role` attribute issue.

**Comment by MelissaBraxton** [comment]
Sweet! @jasnakai - can you link that last PR please?  Then I think we can move this to in review and close it out after the PR is merged.

**Comment by jasnakai** [comment]
PR: [Removed unneeded ARIA role attributes from nav and footer elements #3715](https://github.com/18F/18f.gsa.gov/pull/3715)

**Comment by jasnakai** [comment]
@MelissaBraxton All set! Sorry for the delay. Let me know if it needs anything else. Thank you!
