### ISSUE TITLE
Remediate 18F website home page accessibility bugs

### ISSUE THREAD

**Issue by jasnakai** [18F/TLC-crew#213]
### A description of the work
This work is based off of findings from an accessibility audit performed for ticket [#121](https://github.com/orgs/18F/projects/41/views/1?pane=issue&itemId=25040967). 
Documentation of the home page accessibility bugs can be reviewed and [found here](https://docs.google.com/document/d/1RwacqFlZQJa7-jeZyZJdE0w1e6rrm5kwDxZBysdeTX0/view).

List of bugs:
- The following issues are related to the implementation of the Card component
  - Improper use of anchor tag
  - Use of negative tabindex
  - Skipped heading level

### Point of contact on this issue
- @jasnakai

### Billable?
- [ ] Yes
- [x] No
If yes, tock code:

### Skills needed
- Frontend Dev

### Acceptance Criteria
- [ ] Remediate the documented home page accessibility issues 

### Tasks
- [ ] Create a pull request with issue(s) remediated
- [ ] Tag @jasnakai and @alexbielen as reviewers
