### ISSUE TITLE
Remediate 18F website What We Deliver/[SUBPAGES] accessibility bugs

### ISSUE THREAD

**Issue by jasnakai** [18F/TLC-crew#217]
### A description of the work
This work is based off of findings from an accessibility audit performed for ticket [#121](https://github.com/orgs/18F/projects/41/views/1?pane=issue&itemId=25040967). 

Documentation of the What We Deliver/[SUBPAGES] accessibility bugs can be reviewed and [found here](https://docs.google.com/document/d/1ijBREMLbH6a0NoWaS0BM94vc81z3mfcuJ2yNMOn4Pi0/view).

List of bugs:
- Skipped heading level
- Button (interactive element) inside an anchor tag
- `<blockquote>` element cannot be a direct descendant of a `<ul>` element

### Point of contact on this issue
- @jasnakai

### Billable?
- [ ] Yes
- [x] No
If yes, tock code:

### Skills needed
- Frontend Dev

### Acceptance Criteria
- [ ] Remediate the documented What We Deliver/[SUBPAGES] accessibility issues 

### Tasks
- [ ] Create a pull request with issue(s) remediated
- [ ] Tag @jasnakai and @alexbielen as reviewers

**Comment by mel-keene-gsa** [comment]
@MelissaBraxton I was unable to work on this due to IT issues (locked out of my computer for a few days). I'll put back into the prioritized backlog and unassign myself.
