### ISSUE TITLE
Create Project Health form in airtable, gather feedback and update

### ISSUE THREAD

**Issue by janelx** [18F/TLC-crew#226]
### A description of the work
_This is part 2 of 3 issues on updating project health. Previously completed ticket_: [Project Health update #187](https://github.com/orgs/18F/projects/41/views/1?pane=issue&itemId=27154524)

Project Health has been done differently by different 18F teams, and this means that the data collected isn't consistent or useful for the intended outcomes. LT members and AMs have tried to rework PH, but this hasn't landed.
We need a single way to collect Project Health information on a consistent reporting cadence across 18F teams (the start of "the 18F Way") so that all the stakeholders for PH information find it valuable and so that we have one process to iterate on instead of reinventing wheels.
We also need a plan to communicate and roll this out as change management across 18F.

### Point of contact on this issue
@SelenaJV will be Manager and Approver (in MOCHA framework)
@Erica-Perkins should be Consulted

### Reproduction steps (if necessary)
DA Team couldn't figure out how to do PH among the myriad ways already present in 18F.
LT already struggles to understand and make good use of PH reported data.
This process isn't working for anybody.
We need to fix it.

**Billable?**
No

**Skills needed**

X Any human
 Design
 Content
 Engineering
 Acquisition
 Product
 Other: Account Management

**Timeline**
Does this need to happen in the next two weeks?
 No

**How much time do you anticipate this work taking?**
Likely a full 2 weeks.

### Tasks

- [ ] Create airtable project health form and dashboard (consult w/Kelsey)
- [ ] Gather feedback from stakeholders: Selena, Erica, Andrew and AMs - maybe additional supes?
- [ ] Test with a few project teams
- [ ] Share with 18F (may be it's own ticket - depending on timing)

Docs
[Project health discovery and planning notes](https://docs.google.com/document/d/1hZAmc3sEBsgwErqq37qyvmLvcrPA25SDnQ-e430FNSo/edit#heading=h.tn2eb9uomeec) - Outlines background, goals and values of project health (in progress).
[Project Health form - Working draft](https://docs.google.com/document/d/1FxJFvS4O36awr0j90DabBvohDJjWkgincxFF_1EykZM/edit)

**Comment by MelissaBraxton** [comment]
Whoever picks this up will want to get access to Airtable from @kfoley-18F and chat with her about how to make changes without breaking things.

**Comment by janelx** [comment]
In prep for review I created a feedback form for [project health updates.](https://forms.gle/18TpwZ7k6fmrSrPf9). [Editable form](https://docs.google.com/forms/d/1CIV3hhEveQbCHQmahLO4PR-SqGqD4wAKmh_xeVJqCK4/edit)

**Comment by janelx** [comment]
@adunkman @SelenaJV Project health form is in Airtable. [Form ](https://airtable.com/shr2Hr9MWCsUophxL) and [editable form](https://airtable.com/appsLLLryeqBK2V9d/tblXkMeg076YN4oba/viwnfjBXGwxzVFrK2?blocks=hide) if you'd like to review. I will reach out to @Erica-Perkins to coordinate getting feedback from AMs.

**Comment by SelenaJV** [comment]
Thanks @janelx. I've handed this work off to Andrew. He's on leave this week.

**Comment by janelx** [comment]
Today is my last day on TLC. Quick update for this ticket:

- Review from AMs: I've posted in a call for review in AM channel per @Erica-Perkins's request. So far we have 1 response. You can see [responses here](https://docs.google.com/forms/d/1CIV3hhEveQbCHQmahLO4PR-SqGqD4wAKmh_xeVJqCK4/edit)
- Piloting/testing with two project teams: Need to identify 2-3 teams and remove "test data" question on form. 
- Dashboard is ready to created - consult @adunkman for data points to include

Feel free to reach out to me with any questions!

**Comment by MelissaBraxton** [comment]
@kfoley-18F  - Do you think this work could be lumped in with your Airtable working group?

**Comment by kfoley-18F** [comment]
Yes - I can add the follow-up parts of this ticket to that working group (if I get some people raising their hands for it!)

**Comment by MelissaBraxton** [comment]
@alexsobledotgov, @NatashaJIbrahim, @elieberkowitz  - When y'all are ready to consider how you's pick up work on the project health form, take a look at this issue and reach out to us so we can fill you in on what's been done so far!

**Comment by alexsobledotgov** [comment]
@MelissaBraxton Will do, thanks for the note! As a heads up, we probably won't be picking up Project Health Airtable work in the near future. We are starting with other views & dashboards.

**Comment by MelissaBraxton** [comment]
It sounds like a first step here is to create a plan to pilot this with a few 18F teams, what Qs we want to answer, and any changes to the form we recommend.

**Comment by christophermather** [comment]
Having some trouble getting folks to engage, though I may have a bite from one project lead (Colin Murphy). Will schedule some time to walk through the new form and possibly pilot w/ the weather.gov team. Colin is out this week, so testing will need to happen next week.

In the meantime, I'm going to take one or two steps back and do a little skeleton roadmap kind of thing based on desired outcomes. I have a feeling updating the form is just one part of the need here.

**Comment by alexbielen** [comment]
@christophermather do you feel like there's enough here to keep going through the next increment? Melissa and I are figuring out increment planning right now.

**Comment by christophermather** [comment]
I think so, yeah! There's definitely some sense-making that I can do without blockers. 

I'll also do my best to get some feedback on the form, one way or another.

**Comment by christophermather** [comment]
Update: the Weather.gov team is starting to pilot the updated form. They plan to use the form over the next 4-6 weeks. A the end of that time, TLC will reconvene with the project lead (Colin Murphy) and hold a retro to gather feedback (or another feedback mechanism).

A couple notes:

- **The scope of this pilot is intentionally limited.** We are just testing the first hypothesis from [our design research](https://docs.google.com/document/d/1hZAmc3sEBsgwErqq37qyvmLvcrPA25SDnQ-e430FNSo/edit): Clear presentation of the value and need for project health to 18F will increase confidence and rate in filling out project health.
- **The Weather.gov team will use this [Google form](https://docs.google.com/forms/d/e/1FAIpQLSfJ16EJuOweOyZ3vGPj5UkTmat664T378zLtQbl-bAdnyXnMw/viewform) for the pilot.**  Individual contributors will fill out the form each week. The project lead will aggregate the results and then send them through the current FY22 and FY23 [Airtable form](https://airtable.com/appsLLLryeqBK2V9d/shrmGNtY1gakJTWjs).
- **We will test the other hypotheses in a future phase.** There is some work that will need to be done to implement in Airtable and some decision-making with LT about when to test.

**Comment by MelissaBraxton** [comment]
@christophermather  -  If you want to spin up a new issue that covers work to be done at the end of the pilot period, we can call this issue done.

**Comment by christophermather** [comment]
Done! https://github.com/18F/TLC-crew/issues/413
