### ISSUE TITLE
Project Health: Discover and document different ways to facilitate

### ISSUE THREAD

**Issue by janelx** [18F/TLC-crew#227]
### A description of the work
This is part 3 of 3 issues on updating project health. 

- [x] Part 1: [Project Health update #187](https://github.com/orgs/18F/projects/41/views/1?pane=issue&itemId=27154524)

- [ ] Part 2: [Create Project Health form in airtable, gather feedback and update#226](https://github.com/18F/TLC-crew/issues/226)

Project Health has been done differently by different 18F teams, and this means that the data collected isn't consistent or useful for the intended outcomes. LT members and AMs have tried to rework PH, but this hasn't landed.
We need a single way to collect Project Health information on a consistent reporting cadence across 18F teams (the start of "the 18F Way") so that all the stakeholders for PH information find it valuable and so that we have one process to iterate on instead of reinventing wheels.
We also need a plan to communicate and roll this out as change management across 18F.

### Point of contact on this issue
@SelenaJV will be Manager and Approver (in MOCHA framework)
@Erica-Perkins should be Consulted

### Reproduction steps (if necessary)
DA Team couldn't figure out how to do PH among the myriad ways already present in 18F.
LT already struggles to understand and make good use of PH reported data.
This process isn't working for anybody.
We need to fix it.

**Billable?**
No

**Skills needed**

X Any human
 Design
 Content
 Engineering
 Acquisition
 Product
 Other: Account Management

**Timeline**
Does this need to happen in the next two weeks?
 No

**How much time do you anticipate this work taking?**
Likely a full 2 weeks.

### Tasks
- [ ] Research and discover different ways to facilitate completing project health form as a team
- [ ] Create a document on the different ways teams can facilitate completing the project health form

**User story**

- As an 18F project team member I would like to find an effective way of completing the project health form as a team that works for my team (size, dynamics, timing, etc)

**Acceptance Criteria**
- [ ] Document that includes different ways of completing the project health form that meets the goals of the activity and form (outlined at top of form)

Docs
[Project health discovery and planning notes](https://docs.google.com/document/d/1hZAmc3sEBsgwErqq37qyvmLvcrPA25SDnQ-e430FNSo/edit#heading=h.tn2eb9uomeec) - Outlines background, goals and values of project health (in progress).
[Project Health form - Working draft](https://docs.google.com/document/d/1FxJFvS4O36awr0j90DabBvohDJjWkgincxFF_1EykZM/edit)
