### ISSUE TITLE
Research and develop a proposal for how to socialize the MVP "resources by project phase" and where it should live

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#233]
### A description of the work
**Problem statement:** We have a lot of helpful resources. But people can't find them and/or don't always know about or use them consistently. Our new inventory of resources organized by project phase is liable to go unused if people don't know about it and/or can't find it. The impact of this would be maintaining the status quo where people struggle to know what resources are most relevant to them at any given point on their project.

The scope of this issue is to research and write up a proposal for how to socialize the MVP "inventory of links/resources by project phase" that came out of #175 to 18F staff, recommend when, how and at which project milestones it should be introduced to 18F teams, and where it should live so that 18F staff know it exists and can find it when they need it. 

Whoever picks this up has leeway to specify what kinds of research methods and other deliverables they think will be most helpful in supporting the proposal (mental model diagram, stakeholder influence map, communication plan, etc).   

**What's not in scope for this issue (but will need to come later):** Getting alignment on and carrying out the proposal.  

The proposal should address:
 - What is being proposed
 - Why we're proposing it (the problem statement) 
 - How we'll address the problem
 - Who will carry out the proposal
 - When 

This work may compliment #224, but could also be done separately. 

### Point of contact on this issue
@MelissaBraxton 

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [X] Any human
- [X] Design
- [X] Content
- [ ] Engineering
- [ ] Acquisition
- [X] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [ ] No

How much time do you anticipate this work taking?
~ 2 weeks

### Acceptance Criteria

- [ ] We have a proposal for how we'll socialize the MVP "resources by project phase" and where it should live. 

### Tasks
- [x] Research
- [x] Draft proposal
- [x] Share with @alexbielen and @MelissaBraxton for review
- [x] Refine based on feedback

**Comment by MelissaBraxton** [comment]
Thanks @egamble23! This is looking good! Left a few answers to your Qs, and a few little comments / areas to clarify. Once those are addressed, we can move this to done!

I made #254 as an epic to cover executing on this plan and #255 for Alex and I to start tackling first steps.

**Comment by egamble23** [comment]
Thank you, @MelissaBraxton, for the feedback and comments! 

I've resolved the edits and had a couple ideas around the name. Could you please take a look when you get the chance?

Thanks! And thanks for creating follow-ons for this work!

**Comment by MelissaBraxton** [comment]
All righty! @egamble23 - I've resolved a few and added a few more comments. Almost there!

**Comment by egamble23** [comment]
Thank you! I've accepted/resolved and responded to them. If you're okay with the approach of highlighting the placeholder name for now until a name is further shaped by the feedback, I think this can be moved to done. I've highlighted the different mentions in the doc for now. 

Canon, creed, or approach could be good options, depending on stakeholder feedback on what kind of tone to go for, in my humble opinion. :) Thanks!

**Comment by egamble23** [comment]
@MelissaBraxton, just a friendly heads up, Laura Gerhardt reached out about this draft plan. I've shared the draft's link with her since it sounds like she's has done a lot of valuable thinking about the concepts in the project phase framework/approach itself. 

I let her know it's a draft and may evolve over time, and I'll be going to a project starting on Monday.

Hope that all works okay! Just wanted to communicate across teams.
