### ISSUE TITLE
Remediate 18F How We Work accessibility bugs

### ISSUE THREAD

**Issue by jasnakai** [18F/TLC-crew#237]
### A description of the work
This work is based off of findings from an accessibility audit performed for ticket [#121](https://github.com/orgs/18F/projects/41/views/1?pane=issue&itemId=25040967). 

Documentation of the How We Work accessibility bugs can be reviewed and [found here](https://docs.google.com/document/d/1GT51H357wWJ6GYoIbw4tAgeLY4PuwGWKqPsoVLb4pug/view).

List of bugs:
- Image Alt Text set to “Alt Text”
- Redundant use of `<hr>`

### Point of contact on this issue
- @jasnakai

### Billable?
- [ ] Yes
- [x] No
If yes, tock code:

### Skills needed
- Frontend Dev

### Acceptance Criteria
- [x] Remediate the documented How We Work page accessibility issues 

### Tasks
- [x] Create a pull request with issue(s) remediated
- [x] Tag @jasnakai and @alexbielen as reviewers

**Comment by mel-keene-gsa** [comment]
https://github.com/18F/18f.gsa.gov/pull/3701
