### ISSUE TITLE
Identify or develop a project plan template using project phases.

### ISSUE THREAD

**Issue by adunkman** [18F/TLC-crew#240]
### A description of the work

We ask our teams to understand if they are on track to deliver within the timeframe of the project, but provide limited support to plan for the overall arch of a partner engagement across [project phases](https://docs.google.com/document/d/1GTyor4wV87QXLIutMh__pg0FZTG--NY9XCfvdlFw6fQ/edit#heading=h.gthrqcuqvo5s). As a project nears the end of obligated funding or the agreement end date, it becomes increasingly important to understand where we are and if we are on track — but without a mechanism for having this conversation intentionally, teams rely on ✨ vibes ✨ or miss delivering on outcomes of later phases. 

Note: this is about 18F team project planning, not partner product roadmapping.

Examples of similar tools:

- [18F Vermont Timeline & Strategy Outline](https://docs.google.com/spreadsheets/d/1B_x4NXkezbMM-W2s7l2NEOFREzJA0ahvtV0ZpwWJvxs/edit#gid=0)
- [Project timeline - DEIA particant database w Tracker](https://docs.google.com/document/d/1IuHZRzEKS4W3aMdiRokxkG_8EsZH6XZMKgeG-Yfg6aI/edit)
- [DOJ FOIA.gov: Timeline](https://docs.google.com/spreadsheets/d/1xACpo-V5hlj1kIVp42iq-DeNvH__0wIxyrv7VWFwlO8/edit#gid=1695877954)
- [REUSABLE: PA+E&I timeline slides](https://docs.google.com/presentation/d/1dhiNlLzjg14nshapIskBISAw3JlMOv8prH6RqxUu_lI/edit#slide=id.g4c9b4c59ed_0_266)
- Probably more!

### Point of contact on this issue

@adunkman

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?

2-4 days? 🤷‍♂️ 

### Acceptance Criteria

- [ ] As a project team member, I need a tool to track expected work against calendar dates so that I can set and re-set realistic expectations with partners.
- [ ] As a project team member, I need the tool to be continually edited as I iterate on what is needed for the project so that it continues to be useful as the project progresses.
- [ ] As a project team member, I need the tool to support adding high-level chunks of work so that we can track overall anticipated timelines.
- [ ] As an Account Manager, I need the tool to identify when the projected funding end date or agreement end date is (whichever is sooner) so that I can plan for either working with the team to cut scope or working with the partner to extend the dates.
- [ ] As the Chief of Delivery, I need the tool to cover all [project phases](https://docs.google.com/document/d/1GTyor4wV87QXLIutMh__pg0FZTG--NY9XCfvdlFw6fQ/edit#heading=h.gthrqcuqvo5s) so that project teams have time to address perceived risks while reducing stress, and are funded through closeout so they can share their lessons learned from projects.

**Comment by MelissaBraxton** [comment]
Another example that could be helpful to view: https://docs.google.com/spreadsheets/d/1sakWXvxUd68Nf7u2UBf7jkRM28xCD30VRuOv6Aklsmg/edit#gid=422103449

**Comment by MelissaBraxton** [comment]
@donnykwan  - I think this belongs in "in progress" ? The acceptance criteria here are now quite big.  I'm wondering if we can break this issue up into concrete next chunks of work on this?

**Comment by donnykwan** [comment]
I would ask @adunkman to review and decide what the next step will be.

**Comment by donnykwan** [comment]
@adunkman this is the research [result and proposal.](https://docs.google.com/document/d/1gp0J2T6O6n9aq7cH4_TdCmmA5wceqBzUNU2uELrXeDM/edit#heading=h.eycg7mg5f2nv)

**Comment by alexbielen** [comment]
Discussion from Increment Planning: 

- [ ] Donny is going to set up an alignment meeting with Andrew that will generate next steps for this work
- [ ] Chris will join the ticket to help work on next steps

**Comment by christophermather** [comment]
Update (also shared in Friday's sync): Donny and Chris met with Andrew. Current proposal will not meet Andrew's needs. Donny and Chris have met to brainstorm and are developing a new prototype/proposal to share w/ Andrew before he is OOO starting Thursday.

**Comment by MelissaBraxton** [comment]
@donnykwan and @christophermather  - Per our discussion in retro today, and looking at the acceptance criteria that have been added here, this issue is near epic proportions. Between now and our end of day Monday, could the two of you create a new issue for the next step on this that would be achievable in the next increment?

**Comment by christophermather** [comment]
Basically yes! The only complicating factor is that we actually have a [new prototype](https://docs.google.com/spreadsheets/d/1tkHcojNJtdaGqMtbLL4hwBwHHlXPThuTANFf-gt-ukM/edit#gid=34199553) that's ready to run by Andrew. He's OOO until Monday, though, so we're unable to share with him. We're demo'ing with a couple of folks to get some feedback in the meantime. 

For next steps, I could use some help... is it as simple as something like:

- Demo tool w/ COD, gather feedback + implement. 
- Demo tool w/ AMs and project leads, gather feedback on viability
- Determine primary user of tool (this remains unclear)
- ???

@donnykwan what do you think?

**Comment by donnykwan** [comment]
We are still doing hit and miss, but I agree with @christophermather that we shall show the couple of "prototypes" to gauge if that is the right "direction" we are heading.  If not, then we will work with Andrew to write a new issue/user story.

**Comment by donnykwan** [comment]
Just want to document here the report for sprint 1 is [here](https://docs.google.com/document/d/1gp0J2T6O6n9aq7cH4_TdCmmA5wceqBzUNU2uELrXeDM/edit#heading=h.eycg7mg5f2nv).

**Comment by MelissaBraxton** [comment]
Cool! Let's revise this issue to call this first part done with the delivery of the report and initial prototype, and then document your next steps as a new issue(s).

**Comment by christophermather** [comment]
OK! I've put in a new issue. It's scoped nice and small, but with some recs on follow-up tickets once we've chatted w/ Andrew.

Here's the ticket: https://github.com/18F/TLC-crew/issues/331

**Comment by christophermather** [comment]
Also, reminder that I'm out next week, but will be back in office 7/24.

**Comment by MelissaBraxton** [comment]
First steps are done. Moving the epic out of "in progress," and the work will continue in #331.
