### ISSUE TITLE
Remediate 18F website Blog accessibility bugs

### ISSUE THREAD

**Issue by jasnakai** [18F/TLC-crew#274]
### A description of the work
This work is based off of findings from an accessibility audit performed for ticket [#121](https://github.com/orgs/18F/projects/41/views/1?pane=issue&itemId=25040967). 
Documentation of 18f Blog accessibility bugs can be reviewed and [found here](https://docs.google.com/document/d/1smNEhXiYSZj_YCcFuEb6qwNjVT8rNnlxrgjwC0eqT-E/view).

List of bugs:
- Skipped heading level
- Improper use of `<a>` in blog post summaries
- Blog post pagination does not need to be a header

### Point of contact on this issue
- @jasnakai

### Billable?
- [ ] Yes
- [x] No
If yes, tock code:

### Skills needed
- Frontend Dev

### Acceptance Criteria
- [ ] Remediate the documented accessibility issues 

### Tasks
- [ ] Create a pull request with issue(s) remediated
- [ ] Tag @jasnakai and @alexbielen as reviewers
