### ISSUE TITLE
Remediate 18F website Contact accessibility bugs

### ISSUE THREAD

**Issue by jasnakai** [18F/TLC-crew#275]
### A description of the work
This work is based off of findings from an accessibility audit performed for ticket [#121](https://github.com/orgs/18F/projects/41/views/1?pane=issue&itemId=25040967). 
Documentation of 18f Contact accessibility bugs can be reviewed and [found here](https://docs.google.com/document/d/14BEYBmsbtZ-y2oQfqL4YMoa4ki8bLBoXU2fdqsNXBLc/view).

List of bugs:
- Skipped heading level
- Improper use of `<a>` on social media links

### Point of contact on this issue
- @jasnakai

### Billable?
- [ ] Yes
- [x] No
If yes, tock code:

### Skills needed
- Frontend Dev

### Acceptance Criteria
- [ ] Remediate the documented accessibility issues 

### Tasks
- [ ] Create a pull request with issue(s) remediated
- [ ] Tag @jasnakai and @alexbielen as reviewers
