### ISSUE TITLE
Build combined Guides and Methods infrastructure

### ISSUE THREAD

**Issue by alexbielen** [18F/TLC-crew#276]
Part of the Guides Replatforming Epic #269

### A description of the work
The first step in the Guide and Methods replatforming work (see Tech Spec) is to build out the initial architecture for the combined Guide and Methods.

A new 18F GitHub repository should be created for the consolidated guides. We propose naming the repository “approaches” for now, but we are tracking content strategy work on the name as well, so be aware that this is subject to change. Existing Guides repositories will be consolidated into a single GitHub repository, with the old repositories being archived after the replacement implementation is live and publicly available.

### Point of contact on this issue
@alexbielen 

**Billable?**

- [x] No

**Skills needed**

- [x] Engineering

How much time do you anticipate this work taking?

Roughly two weeks.

### Steps and Acceptance Criteria

Create new repository

- [x] In Github, start a new repo.
- [x] Name it “approaches”
- [x] Once created add @MelissaBraxton , @alexbielen, @adunkman, @geekygirlsarah, and @igorkorenfeld as administrators 
- [x] Set correct branch protections on main so it can’t  be pushed to directly, and add repository rules to require at least one reviewer to merge a PR

Copy Handbook files to new guides repo

- [x] Clone the ~TTS Handbook repo~ cloud.gov pages 11ty repo
- [x] Clone the new guides repo
- [x] ~Copy the files from the Handbook to the guide.~ Copy any additional Handbook files over to help configure this new site
- [x] Remove the content files (except an index/home file) and see if the site still runs

Set up a working CI/CD process

- [x] Use the pre-existing Handbook .github/workflows/pull-request.yml file
- [x] Remove the codeql-analysis.yml and stale.yml files (for now)
- [x] Comment out all the jobs except “steps” (as that’s the one that will build)
- [x] Make a PR to add this in and see if it runs without errors

Connect the repo to Cloud Pages

- [x] Log into Cloud Pages
- [x] Connect the new repo to CP
- [x] Set “node” as the starting command
- [x] Check the initial preview build worked correctly
- [x] Update the Handbook README with proper instructions to run/build (if they have changed) and references to the guides

**Comment by geekygirlsarah** [comment]
And it exists!  https://github.com/18F/approaches
