### ISSUE TITLE
Prepare the Guides and Methods for additional guides

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/TLC-crew#283]
Part of the Guides Replatforming Epic #269

### A description of the work

For the Guides and Methods replatforming work (see [Tech Spec](https://docs.google.com/document/d/1lByvjE1xwtdKzn4jhUGYiwMKJLBJug6TqatcKVe2C5o/edit#), we need to make sure the barebones site from #276 is set up to take in additional guide content and assets. This will include adding directories or moving 11ty files in such a way to set up a structured system to make it easier to work with each guide within the project.

### Point of contact on this issue
@alexbielen 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
1-2 days

### Acceptance Criteria

- [x] Ensure common elements (USWDS among others) are pulled out in a place that all guides can use them.
- [x] Set up a directory hierarchy that ensures all the guide content can be imported and structured logically
- [x] Set up an assets directory that ensures all common guide images, stylesheets, and scripts are available to all guides
