### ISSUE TITLE
Add in Agile content to new replatformed Guides and Methods

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/TLC-crew#284]
Part of the Guides Replatforming Epic #269

### A description of the work

For the Guides and Methods replatforming work (see [Tech Spec](https://docs.google.com/document/d/1lByvjE1xwtdKzn4jhUGYiwMKJLBJug6TqatcKVe2C5o/edit#), we need to add in the Agile Guide into the site, including content (Markdown files) and assets (images, CSS files, JS files, any additional files).

### Point of contact on this issue
@alexbielen 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
Less than a week

### Acceptance Criteria

- [x] Copy over the Markdown files to an agile/ folder in the content section
- [x] Copy over the assets to an agile/ folder in the assets section
- [x] Ensure the site builds and the pages are accessible at expected URLs
- [x] Link to the guide on the home page
- [x] Update any broken tags (like {{ site.baseurl}} ) and ensure the layouts work
- [x] Ensure permalink frontmatter points to the right places
- [ ] Move over any special README or wiki content
- [ ] Ensure any special CI/CD steps are incorporated into the new CI/CD workflow
