### ISSUE TITLE
Add in Brand content to new replatformed Guides and Methods

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/TLC-crew#286]
Part of the Guides Replatforming Epic #269

### A description of the work

For the Guides and Methods replatforming work (see [Tech Spec](https://docs.google.com/document/d/1lByvjE1xwtdKzn4jhUGYiwMKJLBJug6TqatcKVe2C5o/edit#), we need to add in the Brand/Visual Identity Guide into the site, including content (Markdown files) and assets (images, CSS files, JS files, any additional files).

### Point of contact on this issue
@alexbielen 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
Less than a week

### Acceptance Criteria

- [x] Copy over the Markdown files to a brand/ folder in the content section
- [x] Copy over the assets to an brand/ folder in the assets section
- [x] Ensure the site builds
- [x] Ensure the pages are accessible at expected URLs
- [x] Link to the guide on the home page
- [x] Update any broken tags (like {{ site.baseurl}} ) and ensure the layouts work
- [ ] Ensure the styles render
- [x] Ensure the download links all work
- [x] Ensure permalink frontmatter points to the right places
- [x] Move over any special README or wiki content
- [x] Ensure any special CI/CD steps are incorporated into the new CI/CD workflow

**Comment by geekygirlsarah** [comment]
I started a draft PR for this. I put what's done and not done yet as comments on that.

**Comment by geekygirlsarah** [comment]
I had moved this back to backlog but saw I shouldn't, so I moved it back to "in progress"

**Comment by MelissaBraxton** [comment]
Adding in review checklist for when the time comes:

- [ ] Make sure there's some icon on the home page that links to the guide
- [ ] visit every page in the main navigation and sidebar navigation to make sure they load
- [ ] Click at least a couple of links within the guide pages to make sure they navigate to the correct guide page
- [ ] The title on every page should be the 18F logo and the name of the guide
- [ ] Check that all images on the production guides match the same images on the new guides
- [ ] Look for any stray { ... } or {{ ... }} type curly brace tags. They shouldn't be visible on these pages.
- [ ] Make sure the appropriate navigation shows up on every page (and not a test menu)
- [ ] Make sure the navigation menus on new and old guides have all the same links
- [ ] Internal/private links (like Google Docs) should have a lock icon and Slack channel links should have a Slack icon
- [ ] Page aesthetics should be about the same across all pages. (like one page isn't wider than others, different font sizes, etc.)
- [ ] The main USWDS-type theme should be on each page. (18F icon, search bar, "An official website of the US gov", GSA footer, etc.)

You do NOT have to read the guides for correct grammar, correct methods, or test if those work. This is just a technical review to make sure content is integrated correctly. (If you notice mistakes in this regard, file issues instead!)

**Comment by alexbielen** [comment]
This one is in progress but will need a new assignee at the 7/18 increment planning with @geekygirlsarah heading out

**Comment by beechnut** [comment]
@igorkorenfeld Is there a place we're supposed to put Guide-specific stylesheets (I'm working on the [Brand guide's color matrix](https://github.com/18F/brand/blob/8fa0a02e115286dace5301ebedc00932b4dd9328/_sass/_color-matrix.scss#L127), for example)?

**Comment by beechnut** [comment]
I'm currently blocked: the styles aren't loading, despite being in the right place. Could use help resolving.

**Comment by beechnut** [comment]
Okay, raising a bigger blocker to @MelissaBraxton @alexbielen:

Yesterday, @igorkorenfeld and I paired to make some improvement to style rendering.

However, the styles are still significantly broken. I think that trying to fix styles for this guide alone by loading styles from the Brand guide risks overwriting and breaking styles across the Guides. This seems like a bigger issue, perhaps to be solved at the overall Guides level.

**Comment by beechnut** [comment]
When we talked about this at a recent sync (I believe last Friday), it was decided (I believe by @MelissaBraxton) that we'd let the issue of conflicting styles be a separate unit of work, and that it's ok that the styles have some rendering issues for the moment.

I'll be submitting this issue for review later today.

**Comment by beechnut** [comment]
This is ready for review! I added @MelissaBraxton @alexbielen and @igorkorenfeld as reviewers.

**Comment by alexbielen** [comment]
Re: conflicting styles -- 

For the benefit of any future thread readers https://github.com/18F/TLC-crew/issues/355 captures the conflicting styles issue.
