### ISSUE TITLE
Add in Engineering content to new replatformed Guides and Methods

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/TLC-crew#288]
Part of the Guides Replatforming Epic #269

### A description of the work

For the Guides and Methods replatforming work (see [Tech Spec](https://docs.google.com/document/d/1lByvjE1xwtdKzn4jhUGYiwMKJLBJug6TqatcKVe2C5o/edit#), we need to add in the Engineering Guide into the site, including content (Markdown files) and assets (images, CSS files, JS files, any additional files).

### Point of contact on this issue
@alexbielen 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
Less than a week

### Acceptance Criteria

- [ ] (leaving as draft until we determine if the steps in #284 are correct)

**Comment by MelissaBraxton** [comment]
Adding review checklist for when the time comes:


- [ ] Make sure there's some icon on the home page that links to the guide
- [ ] visit every page in the main navigation and sidebar navigation to make sure they load
- [ ] Click at least a couple of links within the guide pages to make sure they navigate to the correct guide page
- [ ] The title on every page should be the 18F logo and the name of the guide
- [ ] Check that all images on the production guides match the same images on the new guides
- [ ] Look for any stray { ... } or {{ ... }} type curly brace tags. They shouldn't be visible on these pages.
- [ ] Make sure the appropriate navigation shows up on every page (and not a test menu)
- [ ] Make sure the navigation menus on new and old guides have all the same links
- [ ] Internal/private links (like Google Docs) should have a lock icon and Slack channel links should have a Slack icon
- [ ] Page aesthetics should be about the same across all pages. (like one page isn't wider than others, different font sizes, etc.)
- [ ] The main USWDS-type theme should be on each page. (18F icon, search bar, "An official website of the US gov", GSA footer, etc.)

You do NOT have to read the guides for correct grammar, correct methods, or test if those work. This is just a technical review to make sure content is integrated correctly. (If you notice mistakes in this regard, file issues instead!)

**Comment by MelissaBraxton** [comment]
@kewlguy781  - Given that PR is in draft status, I'm thinking this is still in progress?

**Comment by kewlguy781** [comment]
All pages in engineering are now in place. We are still working on cleaning up. See Ticket #336 #337 #338. (#337 is almost done)

**Comment by kewlguy781** [comment]
> The following pages need to be fixed for accessibility:
> 
> engineering/languages-runtimes/css/ engineering/security/incident-response-drills/ engineering/tools/accessibility-scanning/ engineering/tools/docker/ engineering/our-approach/incident-reports/cloud-gov/ engineering/languages-runtimes/javascript/
> 
> [1_pa11y-scan.txt](https://github.com/18F/TLC-crew/files/12177401/1_pa11y-scan.txt)

(This has already been fixed)

**Comment by alexbielen** [comment]
@kewlguy781 I think that I am reading this right, but can you clarify if the accessibility issues still need to be fixed?

Is the remaining work on this ticket #338 and doing the QA review?

**Comment by alexbielen** [comment]
I closed this and broke out the remaining QA work into #375
