### ISSUE TITLE
Add in Derisking content to new platform - Setup & Home [1/4]

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/TLC-crew#292]
Part of the Guides Replatforming Epic #269

### A description of the work

For the Guides and Methods replatforming work (see [Tech Spec](https://docs.google.com/document/d/1lByvjE1xwtdKzn4jhUGYiwMKJLBJug6TqatcKVe2C5o/edit#), we need to add in the De-risking guide into the site, including content (Markdown files) and assets (images, CSS files, JS files, any additional files). Given that this is a large guide this replatforming work should be split into four parts, dividing the work into small pieces. This is ticket refers to part 1/4. 

Action items for this ticket includes:
- Setting up the guide title and navigation
- Porting over the the home page

Related tickets
1. #359
2. #353
3. #360

### Point of contact on this issue
@alexbielen 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
Less than a week

### Acceptance Criteria

- [ ] Copy over the Markdown files to a derisking/ folder in the content section
- [ ] Copy over the assets to an derisking/ folder in the assets section
- [ ] Ensure the site builds
- [ ] Ensure the pages are accessible at expected URLs
- [ ] Link to the guide on the home page
- [ ] Update any broken tags (like {{ site.baseurl}} ) and ensure the layouts work
- [ ] Ensure the styles render
- [ ] Ensure the download links all work
- [ ] Ensure permalink frontmatter points to the right places
- [ ] Move over any special README or wiki content
- [ ] Ensure any special CI/CD steps are incorporated into the new CI/CD workflow

**Comment by igorkorenfeld** [comment]
Update ticket reflecting the split up work

**Comment by igorkorenfeld** [comment]
Further subdivided the work

**Comment by igorkorenfeld** [comment]
[PR](https://github.com/18F/approaches/pull/43/files) for this work

**Comment by alexbielen** [comment]
Looks like this was closed in https://github.com/18F/approaches/pull/43/files 

Closing this!
