### ISSUE TITLE
Make content updates to the 18F website and adjust front end code as needed

### ISSUE THREAD

**Issue by durland18F** [18F/TLC-crew#317]
##A description of the work
This issue covers content updates to the 18F website and is a a partial replacement of issue #313. 

We have written new content and navigation for the site, and need someone to put in the content, check on the look and feel with the new content in the old design, and make any front-end code adjustments to make sure it works and is presentable. 

The new content can be found in [this copy deck](https://docs.google.com/document/d/1CA-um7FWudmwLSRNcag3tCV7LKdqDUH_PXgxM-kmQD0/edit#heading=h.1q9gvxvareq).

##Point of contact on this issue
@durland18F 

### Open Questions
We don't really understand yet how much front-end code work is required here; hopefully it will be relatively minor.

**Skills needed**

- [ ] Any human
- [ ] Design
- [X] Content
- [X] Engineering (front-end skills, which exist also within design)
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Billable?

- [ ] Yes
- [X] No
If yes, tock code:

### Timeline
 
Does this need to happen in the next two weeks?
- [x] Yes
- [ ] No
 
### How much time do you anticipate this work taking?
Not sure but shouldn't be more than a few days

### Acceptance Criteria
As a viewer of the 18F site, I can navigate to the site and find the new content and nav, without nav problems or layout issues.

### Possible tasks
- [X] Mock up refinements
- [X]  Set up staging site 
- [X]  Submit a PR to implement new design
- [ ] Conduct user research to inform further site refinements (likely needs to be its own issue)

**Comment by austinhernandez** [comment]
**Question: is there anyway to preserve current copy and add new copy with the ability to display both to users for the purposes of a/b testing to be done at a later date?**

to add more context for this ticket the new content has _not_ been tested. in our design epic planning yesterday (7/5), we thought it would be advantageous to test the new copy without delaying this work. we thought that A/B testing on new copy (the copy in this ticket) versus old copy (currently on the site) should show us how the new content is performing/inform our work going forward.

In speaking to @michelle-rago at standup 7/6 this might be a bit tricky to do a true a/b test due to site traffic. let's discuss further how we might push this new content and preserve the old content to run usability tests on afterward.

**Comment by MelissaBraxton** [comment]
Let's officially remove the task re: testing from this issue and call this done when the content has been updated. @michelle-rago (and/or @AnitaYCheng?)  - if you want to spin up a new issue to test the content, that'd be great! We'll likely not prioritize it for a few increments, but the issue will help us make sure it doesn't fall off the radar.

**Comment by MelissaBraxton** [comment]
@AnitaYCheng and @michelle-rago - w/ removing testing from the scope, I think this is in review, now that the PR is out there.

**Comment by AnitaYCheng** [comment]
@MelissaBraxton Not ready for review yet, @michelle-rago was in the middle of trying some more things with the sidebar layouts on one of the pages.

**Comment by michelle-rago** [comment]
@MelissaBraxton 

Update on this work:
- More content has been written that is part of this update. We should define done for this. Do we want to push new content to production or have a complete branch where LT and others can consider changes (in light of other branding work happening)?
- Hopefully @AnitaYCheng can figure out why a chunk of text won't display on the [Work with us page](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/tlc-copy-07-2023/how-we-work/). I can't figure it out!
- If we keep these changes we should 
- - Change the URLs of the pages (e.g., How we work > Work with us)
- - Remove the code that refers to PA/EI and other offerings
- - Update sidebar images on Work with us
- - Add sidebar heading on Work with us
- - Decide how we want to handle the contact form (Google form, Touchpoints, or just keep the email address).

**Comment by MelissaBraxton** [comment]
Thank you @michelle-rago!

Definition of done for this is (1) new the content is live, new content has been pushed to prod, and (2) we have a new issue (or issues) to cover the next steps you listed: 

-- Change the URLs of the pages (e.g., How we work > Work with us)
-- Remove the code that refers to PA/EI and other offerings
-- Update sidebar images on Work with us
-- Add sidebar heading on Work with us
-- Decide how we want to handle the contact form (Google form, Touchpoints, or just keep the email address).

Would you or Anita be able to translate this list into new issues? Ideally, by end of day today so that we can prioritize this work in the next increment.

**Comment by MelissaBraxton** [comment]
Giving this s bump, it looks like #335 is merged! 🎉  Who should we ping to review the PR on this one so that we can move this to done?  @quarterback , @durland18F
