### ISSUE TITLE
Blog Post on Facilitation

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#319]
### A description of the work
The scope of this issue is a blog post on facilitation. Qituwra started this post before she went on extended leave and is now back and ready to finish it up!

### Point of contact on this issue
@MelissaBraxton  / @LizCamerlin 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [X] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
**About 2 weeks**

### Tasks (at a high level) the detailed steps are all listed out in  blogging guidelines and instructions[ here](https://github.com/18F/blog-drafts)

 - [ ] Review blogging guidelines and instructions[ here](https://github.com/18F/blog-drafts).
 - [ ] Create a new post using the "how do I create a new post" instructions [here](https://github.com/18F/blog-drafts#idea-how-do-i-create-a-new-post)
- [ ] Draft post
- [ ] Go through review and approval process
- [ ] Create new PR to implement post on the 18F website

### Acceptance Criteria

- [ ] The blog post is live on the 18F blog

**Comment by MelissaBraxton** [comment]
@LizCamerlin  - Tagging you as someone Qituwra can work with on this!

**Comment by qmanderson1** [comment]
Hey team! @MelissaBraxton - @LizCamerlin and I will meet next week to talk about this blog. [Here's the current draft!](https://docs.google.com/document/d/1THSKHjhfIEo9Ksb8NVrIg36YHVOQ4RBYARuQ6rpcQE8/edit)

**Comment by MelissaBraxton** [comment]
@qmanderson1  - I just saw your ask for a plain language review on this! 🎉 Ok if I move it in to the "waiting" column?

**Comment by AnitaYCheng** [comment]
I'm doing a plain language review!

**Comment by quarterback** [comment]
This is good to go.

**Comment by qmanderson1** [comment]
Awesome, thank you! @quarterback

**Comment by MelissaBraxton** [comment]
Post went live today, so we can call this done!
