### ISSUE TITLE
Refresh 18F website template website using new content

### ISSUE THREAD

**Issue by austinhernandez** [18F/TLC-crew#320]
### Additional information about the request

- [Updated 18F website copy](https://docs.google.com/document/d/1CA-um7FWudmwLSRNcag3tCV7LKdqDUH_PXgxM-kmQD0/edit#heading=h.1q9gvxvareq)
- [Original Figma mockups shown to leadership](https://www.figma.com/file/e9IPzd9q6wRx5WpgBjWx0i/18F-redesign?type=design&node-id=0%3A1&mode=design&t=5hoHrkTdpbrDfUbs-1). 
- Part of the #313 epic

## Background

@austinhernandez took [updated 18F website copy](https://docs.google.com/document/d/1CA-um7FWudmwLSRNcag3tCV7LKdqDUH_PXgxM-kmQD0/edit#heading=h.1q9gvxvareq) created by @durland18F and @amandacostello and turned them into a [quick site refresh in Figma](https://www.figma.com/file/e9IPzd9q6wRx5WpgBjWx0i/18F-redesign?type=design&node-id=0%3A1&mode=design&t=5hoHrkTdpbrDfUbs-1). The comps were used to show leadership what a website refresh could be and leadership responded positively to the changes. The ask is a design similar to this but this mockup was intended as a proof-of-concept. Images are placeholders and I didn't use USWDS for spacing or grids. It needs to be reworked a bit to match 18F branding, be USWDS-friend(lier), and be production-ready.

The goal is to implement fast, ask questions later. We are trying to go as fast as we can in government speed to show that website updates don't need to take 4 years. We are also going off the assumption that any change is a good change—then doing research (#314 ) to validate.

### Open Questions

- Who gets final sign-off?

### Point of contact on this issue

@austinhernandez 
@quarterback 
 
## Additional Details
- Content only changes are coming first in ticket #317 .
- There are comments in the Figma doc giving additional context.
- This work should not have any dependencies 
  - It should consider future research goals, but happening independently
- This isn't a total 18F style guide (logo, colors, fonts, etc.) refresh
  - [Brand colors](https://brand.18f.gov/) should match
  - A USWDS-adapted layout is a must!
- There is room for flexibility in these constraints as the brand can be _extended_, like updates to illustrations as needed

### Billable?

- [ ] Yes
- [X] No
If yes, tock code:

### Timeline
 
Does this need to happen in the next two weeks?
- [ ] Yes
- [X] No
 
### How much time do you anticipate this work taking?

1-2 increments 

## Acceptance Criteria

 tasks
- [x] There are updates to the existing [Figma document](https://www.figma.com/file/e9IPzd9q6wRx5WpgBjWx0i/18F-redesign?type=design&node-id=0%3A1&mode=design&t=5hoHrkTdpbrDfUbs-1) with a more polished and refined website re-design
- [x] The original design only looked at the homepage and "work with us" page, but more of a template that can be implemented across the site would be more useful for implementation.
- [x] We've created a new issue to implement the refined designs

**Comment by MelissaBraxton** [comment]
Added a comment that we want to create an implementation issue before we call this issue done.

**Comment by MelissaBraxton** [comment]
You can check out the PR that includes the copy changes here: https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/tlc-copy-07-2023/

**Comment by melchoyce** [comment]
This issue is wrapped up and will be continued in #371. See that issue for details.
