### ISSUE TITLE
18F Website: Staging site buildout

### ISSUE THREAD

**Issue by quarterback** [18F/TLC-crew#324]
### A description of the work
There are two phases of this work, the first is to build a production site for 18F website that encompasses the mockups initially designed during the initial phase of the website work. We recognize this will be a site that allows more design research to occur, but in order to reach the next stage of this project, we need a physical staging site built.

### Point of contact on this issue
Ron Bronson (@quarterback)

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [x] Design
- [x] Content
- [x] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes
- [ ] No

How much time do you anticipate this work taking?
TBD

### Acceptance Criteria

- [ ] Having a working staging site

**Comment by quarterback** [comment]
The ask here as far as I can see is 

- [ ] clone existing site into a staging branch 

- [ ] deploy the site in Vercel or Netlify 

- [ ] Make content changes

**Comment by MelissaBraxton** [comment]
I think we can close this one out as the Federalist preview will meet the need here.
