### ISSUE TITLE
Document a decision on the "two sources of truth" and "deferring value delivery/queueing work" problems for the Guides and Methods replatform

### ISSUE THREAD

**Issue by alexbielen** [18F/TLC-crew#332]
### A description of the work
Document an approach to incrementally release the re-platformed Guides and Methods. 

The approach should consider the following things: 

- [x] The "two sources of truth" problem. Currently, as guides are moved into the new repository, the old repositories are still active and are being updated. There are changes being made to Guides after the "pencils down" announcement (e.g., https://github.com/18F/ux-guide has recent changes). There are a number of ways to address this issue so I'd like us to explore those and identify the one that works best. This may not be a widespread issue either, so understanding the impact of this will help us narrow in on the right solution. 
- [x]  We are currently deferring value delivery and queueing work in progress. The re-platformed guides are not viewable by the public. Is it possible for us to completely deliver a single re-platformed guide instead of waiting for all of the guides to be re-platformed to release? I believe that this should be doable with a slight variation in the [Redirecting to New Guides](https://docs.google.com/document/d/1lByvjE1xwtdKzn4jhUGYiwMKJLBJug6TqatcKVe2C5o/edit#heading=h.6jx84cd16951) section of the Tech Spec. 

### Point of contact on this issue
@alexbielen (back on 7/19)

**Skills needed**

- [x] Engineering

### Acceptance Criteria

- [x] A documented decision on what to do about 1) the "two sources of truth" problem and 2) the deferring value/queueing work problem. 
- [x] Updates to the existing issues or new issues as relevant

**Comment by loganmeetsworld** [comment]
- Draw up a small roadmap/release plan and add to the tech spec
- Find appropriate place to document in the /approaches repo
