### ISSUE TITLE
Rename URLs for selected pages on 18F site

### ISSUE THREAD

**Issue by michelle-rago** [18F/TLC-crew#335]
- [x] Rename what-we-deliver to our-work
- [x] Rename how-we-work to work-with-us
- [x] Update internal links
- [x] Add redirects

**Comment by michelle-rago** [comment]
[Slack convo on implementing redirects](https://gsa-tts.slack.com/archives/C02CD5VUQ/p1689780586399139)
