### ISSUE TITLE
Add in Derisking content to new platform – State Guide [2/4]

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/TLC-crew#359]
Part of the Guides Replatforming Epic #269

### A description of the work

For the Guides and Methods replatforming work (see [Tech Spec](https://docs.google.com/document/d/1lByvjE1xwtdKzn4jhUGYiwMKJLBJug6TqatcKVe2C5o/edit#), we need to add in the De-risking guide into the site, including content (Markdown files) and assets (images, CSS files, JS files, any additional files). Given that this is a large guide this replatforming work should be split into four parts, dividing the work into small pieces. This is ticket refers to part 2/4. 

Related Tickets:
1. #292
2. #353
3. #360

Action items for this ticket includes:
- Porting over the content for the State Handbook
- If footnotes have not been setup yet, making sure those are working properly for this guide
- Making sure that sections are bolded in the sidenav as a user scrolls, matching currenting funcationlity.

### Point of contact on this issue
@alexbielen 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
Less than a week

### Acceptance Criteria

- [ ] Copy over the Markdown files to a derisking/ folder in the content section
- [ ] Copy over the assets to an derisking/ folder in the assets section
- [ ] Ensure the site builds
- [ ] Ensure the pages are accessible at expected URLs
- [ ] Link to the guide on the home page
- [ ] Update any broken tags (like {{ site.baseurl}} ) and ensure the layouts work
- [ ] Ensure the styles render
- [ ] Ensure the download links all work
- [ ] Ensure permalink frontmatter points to the right places
- [ ] Move over any special README or wiki content
- [ ] Ensure footenotes are working
- [ ] Ensure the sidenav subnav indicator is working
- [ ] Ensure any special CI/CD steps are incorporated into the new CI/CD workflow
