### ISSUE TITLE
Implement case study content revisions on 18F website

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#373]
### A description of the work
This issues covers implementing re-written case study copy that was created under #346. 

### Point of contact on this issue
@quarterback or @MelissaBraxton 

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [X] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
About a week including reviews

### Acceptance Criteria

- [x] Rewritten case studies, using the new case study structure, are live on the 18F website.

### Tasks
- [x] [Alaska](https://github.com/18F/18f.gsa.gov/pull/3723) – merged
- [x] [DOJCRT](https://github.com/18F/18f.gsa.gov/pull/3731) – merged
- [x] [FBI](https://github.com/18F/18f.gsa.gov/pull/3727) – merged
- [x] [FEC](https://github.com/18F/18f.gsa.gov/pull/3729) – merged
- [x] [Forest Service](https://github.com/18F/18f.gsa.gov/pull/3732) – merged
- [x] [GSA](https://github.com/18F/18f.gsa.gov/pull/3725) – merged
- [x] [State](https://github.com/18F/18f.gsa.gov/pull/3730) – merged
- [x] [Tax Court](https://github.com/18F/18f.gsa.gov/pull/3726) – merged
- [x] [Treasury](https://github.com/18F/18f.gsa.gov/pull/3728) – merged

**Comment by MelissaBraxton** [comment]
@quarterback  - With you out most of the week, can @amandacostello and/or @durland18F review and approve PRs to implement new case study content in your stead?

**Comment by MelissaBraxton** [comment]
- Case study markdown files are in [here](https://github.com/18F/18f.gsa.gov/tree/main/_services_projects)
 - Use the index to navigate to the .md file for the case study you want to edit and open it up.
 - Click the "edit" button (the pencil icon in the upper right corner)
 - Copy and paste in new content / remove old content
 - Click commit changes
 - Choose "create a new branch" 
 - give your branch a descriptive title and fill in the description field before creating the new branch
 - Fill in the relevant pull request template fields
 - Once the pages/build is complete, click "Details" to preview the site
- If it all looks good, add Ron, Amanda, and Jeff as reviewers!

**Comment by ameliaswong** [comment]
@MelissaBraxton All of the PRs are approved or waiting on approval. Should I move this to "In Review" in the meantime?

**Comment by MelissaBraxton** [comment]
Yep, go ahead and move it into review. Also, once the PRs have at least one
approving review, you can go ahead and merge them! :tada: If you want to do
that in co-working or with someone else working alongside, feel free to out!

**Comment by ameliaswong** [comment]
@MelissaBraxton Based on the acceptance criteria, this issue is complete. Should I move to "done" or do you prefer to do that?
