### ISSUE TITLE
Complete QA Checklist for replatformed Engineering Guide

### ISSUE THREAD

**Issue by alexbielen** [18F/TLC-crew#375]
### A description of the work

- [x]  Make sure there's some icon on the home page that links to the guide
- [x]  visit every page in the main navigation and sidebar navigation to make sure they load
- [x]  Click at least a couple of links within the guide pages to make sure they navigate to the correct guide page
- [x]  The title on every page should be the 18F logo and the name of the guide
- [x]  Check that all images on the production guides match the same images on the new guides
- [x]  Look for any stray { ... } or {{ ... }} type curly brace tags. They shouldn't be visible on these pages.
- [x]  Make sure the appropriate navigation shows up on every page (and not a test menu)
- [x]  Make sure the navigation menus on new and old guides have all the same links
- [ ]  Internal/private links (like Google Docs) should have a lock icon and Slack channel links should have a Slack icon
- [x]  Page aesthetics should be about the same across all pages. (like one page isn't wider than others, different font sizes, etc.)
- [x]  The main USWDS-type theme should be on each page. (18F icon, search bar, "An official website of the US gov", GSA footer, etc.)

You do NOT have to read the guides for correct grammar, correct methods, or test if those work. This is just a technical review to make sure content is integrated correctly. (If you notice mistakes in this regard, file issues instead!)

### Point of contact on this issue
@alexbielen 

**Skills needed**

- [x] Any human

How much time do you anticipate this work taking?
1 hour

### Acceptance Criteria

- [x] Checklist is completed

**Comment by AnitaYCheng** [comment]
I believe the "lock icon" and "Slack icon" integrations are known issues to be done later. None of the replatformed guides have them right now.
