### ISSUE TITLE
Research and recommend path forward on sidenav for UX and eng guides

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#407]
### A description of the work
This work is an extension of nav issues that came up in replatforming the UX guide and the engineering guide. Whoever picks up this issue should start by reviewing [this deck](https://docs.google.com/presentation/d/1c6W2zBvlUV8L-hgMqIAhXXmuhfzh5teP100rvHsur00/edit#slide=id.g8a69786df6d67e_5) that provides context, describes the problem, and lays out decisions needed. The scope of this issue is reviewing the deck and how side nav is handled across the guides to recommend: 

- Whether the guides should orient current page with permalinks or page folders
- How many page levels the guides should display in the side nav
- What we should do with heading anchors

### Point of contact on this issue
@alexbielen 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [X] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [ ] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [ ] We've documented decisions on how we'll address:
   - [ ] Whether the guides should orient current page with permalinks or page folders
   - [ ] How many page levels the guides should display in the side nav
   - [ ] What we should do with heading anchors
 

ex: As an 18F staff member who is going on parental leave, I can navigate to my
latest Tock reporting period and choose billing line #1810 by filtering by
number or "extended OOO"

**Comment by MelissaBraxton** [comment]
Aiming to have this done by 9/8!

**Comment by MelissaBraxton** [comment]
@AvivaOskow - Once you have a draft doc, feel free to link it in the issue, move the issue into "in review" and tag @alexbielen and me. After that, I'm guessing we'll add it to our agenda for our next mtg w/ the guides product owner.

**Comment by MelissaBraxton** [comment]
Follow on work to address nav issues is covered in #378 and #338  - We may need to start by updating these or creating new issues, based on the outcome of #420.

**Comment by AvivaOskow** [comment]
Recommendations doc [here](https://docs.google.com/document/d/1S5Wsj36SgQAMHRw61ne5zVD7r-7UFVqhGolsLvnNJvk/edit?usp=sharing)!

**Comment by MelissaBraxton** [comment]
This looks great! Closing as complete, as follow on work is covered under #423
