### ISSUE TITLE
Project reflection request for <team>

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#412]
**Point of contact on this issue**

@claireb-gsa and @peterrowland 

 
**Tock info**
  
By default, we assume project reflections are billable. Add the Tock code here.

**Timeline**
  
Sometime before October
  
  
**Describe the project**

The DOJ / ICM team would like a facilitator to run a project reflection / post mortem focused on the acquisitions aspects of their work. 
  
**Materials for the facilitator**
  
18F has standard project reflection materials:
- [Guide for running a project reflection](https://docs.google.com/document/d/1lB8w_U2SR3X4U78KTOWril_JOINaF98NQwQoR7oYVeo/edit)
- [Template: project reflection conversation guide](https://docs.google.com/document/d/1bsaRrm9Mjnk87UOsHDyTsfK2yVbsnLLywvfFuVXL5HE/edit#)
- [Template: project reflection summary](https://docs.google.com/document/d/1R10zQ5hpHYtSA3utxydte-Xk4ktdjUWnlMOrZp3pSwA/edit)
  

### Acceptance Criteria

- [ ] Review project reflection materials 
- [ ] Schedule and plan for a 90 minute project reflection
- [ ] Facilitate project reflection
- [ ] Summarize project reflection 
- [ ] Share with project team for feedback
- [ ] Share in #project-reflections Slack channel 
- [ ] Use [this form](https://airtable.com/shrDVLEqUpLYGnvKS) to add a link to the completed project reflection summary doc. to the project record in Airtable
- [ ] Share top insights relevant to other teams from the project reflection at the next TLC crew increment demo
