### ISSUE TITLE
Update design tool guidance

### ISSUE THREAD

**Issue by cmajel** [18F/TLC-crew#82]
### A description of the work
[This handbook ticket outlines the work](https://github.com/18F/handbook/issues/3500). Essentially update and clarify our design tool guidance. 

### Point of contact on this issue
You can reach out to me (@cmajel). @quarterback is our current 18F tool holder.

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [x] Design
- [x] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
- Less than two weeks
### Acceptance Criteria

- [ ] A new designer can request design tool licenses according to our current processes using content from the TTS handbook

### Tasks
- [x] Draft guidance
- [x] Get review and approval from
    - [x] 18F design director
    - [x] Tech portfolio contact
- [x] Create a pull request in the TTS Handbook to implement new/revised content; add @MelissaBraxton and @alexbielen as PR reviewers so that we can stay in the loop if there are Qs or refinements needed that come in after you roll off the TLC crew!

**Comment by HannaSChang** [comment]
@cmajel and @quarterback I could use your eyes to review my suggested updates for TTS/18F's design tool guidance, which can be found in [this Google Doc](https://docs.google.com/document/d/1lmU700WjiA1Ox1HZ8TgTBymYksgDa4AlbjVfSwwfFQo/edit?usp=sharing).

The first page contains a description of the issue provided by the requestor (Christine) along with brief instructions on how to review the document. Feedback is much appreciated and feel free to let me know if you have any questions!

**Comment by MelissaBraxton** [comment]
@quarterback  - If you've reviewed and approved, I think once we approve your comments and revisions, i think we can close this out. Is that right, @HannaSChang?

**Comment by HannaSChang** [comment]
@MelissaBraxton - @cmajel will also be reviewing the updated design tool guidance as the owner/requestor of this issue. Once everything has been approved, I can open a PR to implement these changes and move this issue back to the In Progress lane (this is what I've been doing with other issues but let me know if I need to correct my approach in how I handle the tickets/issues). Thanks!

**Comment by cmajel** [comment]
@HannaSChang looks good! I added a comment where we should get a review of the language (happy to help connect if you'd like)

As someone who started recently, is there anything design-tool-wise that you wish had been clearer?

**Comment by HannaSChang** [comment]
@cmajel Good question! As a designer, getting Creative Cloud approved has been a long and confusing process. I submitted a request through GSA's IT help desk, which was pretty straight forward, but their messages to me afterwards have left me with more questions than answers. Maybe once I figure out how to get Creative Cloud approved and installed on my computer, I can update the tool guidance page for that. :P

**Comment by quarterback** [comment]
@HannaSChang there are no more GSA licenses, is what the real issue is.

**Comment by HannaSChang** [comment]
Ah I see, that's good to know. Thanks for the context @quarterback!

**Comment by HannaSChang** [comment]
Posting here to keep track of updates: LaKeisha Russell from The Technology Portfolio is currently reviewing the language for the updated tool guidance.

**Comment by MelissaBraxton** [comment]
I added a task checklist. We can call this issue done once the PR has been created to implement new/revised content.

**Comment by HannaSChang** [comment]
The [design tool guidance draft](https://docs.google.com/document/d/1lmU700WjiA1Ox1HZ8TgTBymYksgDa4AlbjVfSwwfFQo/edit?usp=sharing) has been reviewed by both the 18F Design Director and Tech Portfolio contact. I marked comments as resolved once any questions or suggestions were addressed in the doc. 

@cmajel would you like to take a look at the draft one last time or are we good to create a PR?

**Comment by cmajel** [comment]
👍🏻 Looks good to me! Go forth and PR.
